services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - gdpr-network

networks:
  gdpr-network:
    name: gdpr-network
    external: true
