services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: olgahan
      POSTGRES_USER: olgahan
      POSTGRES_PASSWORD: olgahan
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    ports: ["6380:6379"]

  api:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports: ["8001:8000"]
    volumes:
      - ./backend:/app

  worker:
    build: ./backend
    command: ["celery", "-A", "app.celery_app:celery", "worker", "--loglevel=info"]
    env_file: ./backend/.env
    depends_on:
      - api
      - redis
    volumes:
      - ./backend:/app

  flower:
    image: mher/flower:1.2.0
    command: ["celery", "flower", "--port=5555", "--broker=redis://redis:6379/0"]
    ports: ["5556:5555"]
    depends_on:
      - redis

volumes:
  pgdata:
