services:
  backend:
    container_name: backend
    build: .
    command: sleep infinity
    ports:
      - 8000:8000
    environment:
      - DATA_DIR=/data
      - DB_USERNAME=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_NAME=gdpr
    volumes:
      - .:/app
      - data:/data
    depends_on:
      - db
    networks:
      - gdpr-network

  db:
    container_name: db
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gdpr
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - gdpr-network

networks:
  gdpr-network:
    external: true

volumes:
  data:
  pg_data:
