services:
  backend:
    build: .
    command: sleep infinity
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - data:/data
      - db_data:/db_data
    networks:
      - gdpr-network

networks:
  gdpr-network:
    external: true

volumes:
  data:
  db_data:
