"""Initial Migration

Revision ID: a9f241ac3bee
Revises: 
Create Date: 2025-08-27 16:33:59.134295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f241ac3bee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masking_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_value', sa.String(), nullable=False),
    sa.Column('masked_value', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('IPV4_ADDR', 'MAC_ADDR', 'USERNAME', 'DOMAIN', 'PHONE_NUM', name='rulecategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masking_map_original_value'), 'masking_map', ['original_value'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('IPV4_ADDR', 'MAC_ADDR', 'USERNAME', 'DOMAIN', 'PHONE_NUM', name='rulecategory'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('extracted_size', sa.BigInteger(), nullable=True),
    sa.Column('completed_size', sa.BigInteger(), nullable=False),
    sa.Column('time_remaining', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Enum('TEXT', 'PCAP', 'ARCHIVE', 'JSON', 'UNKNOWN', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'DONE', 'ERROR', name='filestatus'), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('archive_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['archive_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_archive_id'), 'files', ['archive_id'], unique=False)
    op.create_table('preset_rules',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('preset_id', 'rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preset_rules')
    op.drop_index(op.f('ix_files_archive_id'), table_name='files')
    op.drop_table('files')
    op.drop_table('presets')
    op.drop_table('users')
    op.drop_table('rules')
    op.drop_table('products')
    op.drop_index(op.f('ix_masking_map_original_value'), table_name='masking_map')
    op.drop_table('masking_map')
    # ### end Alembic commands ###
