// Heroicons components for the application
export { default as HomeIcon } from '@heroicons/vue/24/outline/HomeIcon'
export { default as DocumentTextIcon } from '@heroicons/vue/24/outline/DocumentTextIcon'
export { default as UsersIcon } from '@heroicons/vue/24/outline/UsersIcon'
export { default as CubeIcon } from '@heroicons/vue/24/outline/CubeIcon'
export { default as CogIcon } from '@heroicons/vue/24/outline/CogIcon'
export { default as ArchiveBoxIcon } from '@heroicons/vue/24/outline/ArchiveBoxIcon'
export { default as BuildingOfficeIcon } from '@heroicons/vue/24/outline/BuildingOfficeIcon'
export { default as TruckIcon } from '@heroicons/vue/24/outline/TruckIcon'
export { default as ChartBarIcon } from '@heroicons/vue/24/outline/ChartBarIcon'
export { default as Cog6ToothIcon } from '@heroicons/vue/24/outline/Cog6ToothIcon'
export { default as PlusIcon } from '@heroicons/vue/24/outline/PlusIcon'
export { default as UserPlusIcon } from '@heroicons/vue/24/outline/UserPlusIcon'
export { default as PlayIcon } from '@heroicons/vue/24/outline/PlayIcon'
export { default as CurrencyDollarIcon } from '@heroicons/vue/24/outline/CurrencyDollarIcon'
